## arg 1:  the new package version
#pre_install() {
	# do something here
#}

post_install() {
	mv /etc/resolv.conf /etc/resolv.conf-dnscryptbak
	echo "nameserver 127.0.0.1" > /etc/resolv.conf
	echo "nameserver 127.0.0.2" >> /etc/resolv.conf
	chattr +i /etc/resolv.conf
}

## arg 1:  the old package version
#pre_remove() {
	# do something here
#}

## arg 1:  the old package version
#post_remove() {
	# do something here
#}
