#!/bin/bash

### 
# Autoconfigure script for Arch Linux and dnscrypt.
#
# This script will set up dnscrypt as a daemon service that runs on
# system startup. It gives you the option to choose which DNSCrypt service to use 
# and easily reconfigure DNSCrypt.
#
# Authors: https://github.com/simonclausen/dnscrypt-autoinstall/graphs/contributors
# Project site: https://github.com/simonclausen/dnscrypt-autoinstall
#
###

# Are you root?
if [ $(id -u) != 0 ]; then
	echo -e "Error!\n"
	echo "You need to be root to run this script."
	exit 1
fi

# Vars for stuff
WHICHRESOLVER=dnscrypteu
GITURL=https://raw.githubusercontent.com/simonclausen/dnscrypt-autoinstall/master/systemd

function config_interface {
	echo -e "\nWhich DNSCrypt service would you like to use?\n"
	echo "1) DNSCrypt.eu   (Europe - no logs, DNSSEC)"
	echo "2) Cisco OpenDNS (Anycast)"
	echo "3) CloudNS       (Australia - no logs, DNSSEC)"
	echo "4) OpenNIC       (Japan - no logs)"
	echo "5) OpenNIC       (Europe - no logs, whitelisted users only)"
	echo "6) OpenNIC       (Toronto, Canada - no logs)"
	echo "7) OpenNIC       (San Francisco, USA - no logs)"
	echo "8) OpenNIC       (Seattle, USA - no logs)"
	echo "9) OkTurtles     (Georgia, USA - no logs)"
	echo "10) Soltysiak.com (Europe - no logs, DNSSEC)\n"
	read -r -p "Select an option [1-10]: " OPTION
	case $OPTION in
		1)
		WHICHRESOLVER=dnscrypteu
		;;
		2)
		WHICHRESOLVER=opendns
		;;
		3)
		WHICHRESOLVER=cloudns
		;;
		4)
		WHICHRESOLVER=opennicjp
		;;
		5)
		WHICHRESOLVER=openniceu
		;;
		6)
		WHICHRESOLVER=opennicca
		;;
		7)
		WHICHRESOLVER=opennicusasfo
		;;
		8)
		WHICHRESOLVER=opennicusasea
		;;
		9)
		WHICHRESOLVER=okturtles
		;;
		10)
		WHICHRESOLVER=soltysiak
		;;
		*)
		exit 1
		;;
	esac
	return 0
}

function config_do {
	curl -Lo /etc/conf.d/dnscrypt-config $GITURL/dnscrypt-config-$WHICHRESOLVER && \
	systemctl restart dnscrypt-proxy
}

echo -e "\nWelcome to dnscrypt-autoinstall.\n"
echo -e "This will autoconfigure DNSCrypt to run as a daemon at start up.\n"
read -n1 -r -p "Press any key to continue..."
clear

echo -e "\nWould you like to see a list of supported providers?"
read -p "(DNSCrypt.eu is default) [y/n]: " -e -i n SHOWLIST

if [ $SHOWLIST == "y" ]; then
	config_interface
fi
config_do

# Run at startup
systemctl is-enabled dnscrypt-proxy || systemctl enable dnscrypt-proxy
