post_install() {
	systemctl daemon-reload
	mv /etc/resolv.conf /etc/resolv.conf-dnscryptbak
	echo "nameserver 127.0.0.1" > /etc/resolv.conf
	echo "nameserver 127.0.0.2" >> /etc/resolv.conf
	chattr +i /etc/resolv.conf
	systemctl is-active dnscrypt-proxy || systemctl start dnscrypt-proxy
}

post_upgrade() {
	systemctl daemon-reload
}

post_remove() {
	systemctl daemon-reload
	rm /etc/conf.d/dnscrypt-config
	chattr -i /etc/resolv.conf
	mv /etc/resolv.conf-dnscryptbak /etc/resolv.conf
}
